// <auto-generated />
using System;
using ManageMe.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageMe.Api.Migrations
{
    [DbContext(typeof(ManageMeDbContext))]
    partial class ManageMeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManageMe.Domain.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AccountEntities");

                    b.HasDiscriminator<string>("discriminator").HasValue("AccountEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ManageMe.Domain.Entities.GoogleAccountEntity", b =>
                {
                    b.HasBaseType("ManageMe.Domain.Entities.AccountEntity");

                    b.HasDiscriminator().HasValue("google");
                });
#pragma warning restore 612, 618
        }
    }
}
